spring:
  redis:
    # 服务器密码
    password: 123456
    # 超时时间
    timeout: 10000ms
    port: 6379
    # 服务器地址
    host: 119.91.218.163
    # 数据库
    database: 6
    lettuce:
      pool:
        # 最大连接数 默认8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
  #rabbitmq
  rabbitmq:
    #服务器地址
    host: 119.91.218.163
    #用户名
    username: admin
    #密码
    password: admin
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息 处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器 默认true
        auto-startup: true
        #被拒绝是重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试 默认false
        enabled: true
        #重试时间 默认1000s
        initial-interval: 1000
        #重试最大次数 默认3次
        max-attempts: 3
        #重试最大间隔时间  默认10000ms
        max-interval: 10000
        #重试间隔的乘数  比如配2.0  第一次等10s 第二次等20秒 第三次等40秒
        multiplier: 1.0




  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 333
    hikari:
      # 连接池名3
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10 maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      #  连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1


# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #  配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package:  com.zhang.seckill.pojo

## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.zhang.seckill.mapper: debug
server:
  port: 8081



